#!/bin/bash

cmake -S . -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_GCP_CLOUD_STORAGE_CONNECTOR=ON \
  -DWITH_GCP_PUBSUB_CONNECTOR=ON \
  -DWITH_AWS_S3_CONNECTOR=ON \
  -DWITH_SQLITE_CONNECTOR=ON \
  -DWITH_POSTGRESQL_CONNECTOR=ON \
  -DWITH_MODBUS_CONNECTOR=ON \
  -DWITH_MQTT_CONNECTOR=ON \
  -DWITH_EMAIL_CONNECTOR=ON \
  -DWITH_HTTP_CONNECTOR=ON \
  -DWITH_SLACK_CONNECTOR=ON \
  -DWITH_AZURE_SERVICE_BUS_CONNECTOR=ON \
  -DWITH_HTTP_LISTENER=ON \
  -DWITH_LUA=ON \
  -DWITH_ZEROMQ_API=ON \
  -DWITH_HTTP_API=ON \
  -DWITH_IMAGE_HANDLERS=ON